branches:
  except:
    - /travis/
    - /github-actions/
    - /doozer/
skip_tags: true
shallow_clone: true

cache:
  - C:\strawberry

install:
  - if not exist "C:\strawberry" cinst strawberryperl
  - set PATH=C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PATH%
  - cd C:\projects\%APPVEYOR_PROJECT_NAME%
  - cpanm --installdeps .

build_script:
  - perl Makefile.PL
  - set HARNESS_TIMER=1
  - gmake test

init:
  - ps: IF ($env:APPVEYOR_REPO_BRANCH -eq "XXX-appveyor-nocache") {$env:APPVEYOR_CACHE_SKIP_RESTORE = "true"; $env:APPVEYOR_CACHE_SKIP_SAVE = "true"}
