branches:
  except:
    - /travis/
    - /github-actions/
    - /doozer/
skip_tags: true
shallow_clone: true

environment:
  matrix:
    - perl: strawberryperl
      # default (probably latest) strawberry version
    - perl: strawberryperl
      strawberry_version: 5.32.1.1

install:
  - if %perl%==strawberryperl if     "%strawberry_version%"=="" cinst strawberryperl
  - if %perl%==strawberryperl if not "%strawberry_version%"=="" cinst strawberryperl --version=5.32.1.1
  - if %perl%==strawberryperl set PATH=C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PATH%
  - cd C:\projects\%APPVEYOR_PROJECT_NAME%
  - cpanm --installdeps .

build_script:
  - perl Makefile.PL
  - set HARNESS_TIMER=1
  - gmake test
